#!/bin/bash
shopt -s expand_aliases
################################################################################
###                                                                            #
### Script:   acro [file]                                                      #
###                                                                            #
### Purpose:  Open Adobe Reader as a separate process, without typing          #
###             ampersand after the filename                                   #
###                                                                            #
### Requires: acroread                                                         #
###                                                                            #
### Returns:  Opens Adobe Reader                                               #
###                                                                            #
################################################################################

acroread "$@" &
