#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: auctex [-c] [-k] [-p paper] [-s] [-v] [-x] file"; echo;
            echo "  -c  compile LaTeX";
            echo "  -k  knit Rnw";
            echo "  -p  a4/letter";
            echo "  -s  sweave Rnw";
            echo "  -v  view";
            echo "  -x  clean"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   auctex [-c] [-k] [-p paper] [-s] [-v] [-x] file                  #
###                                                                            #
### Purpose:  Compile or view LaTeX document from Emacs                        #
###                                                                            #
### Args:     c compiles LaTeX to PDF                                          #
###           k knits Rnw to PDF                                               #
###           p a4 (default) or letter                                         #
###           s sweaves Rnw to PDF                                             #
###           v opens PDF viewer                                               #
###           x cleans intermediate files                                      #
###           file is the LaTeX/Rnw file                                       #
###                                                                            #
### Requires: dvips, ghostview, gs, latex, latexmk, R                          #
###                                                                            #
### Example:  C-c C-c, C-c C-v, C-c C-z                                        #
###                                                                            #
### Returns:  Creates PDF file with same prefix in current directory if        #
###           -c/k/s, otherwise null                                           #
###                                                                            #
################################################################################

action=help
unset dviargs
unset gsargs
while getopts "ckp:svx" A; do
  case $A in
    c) action=compile;;
    k) action=knit;;
    p) dviargs="-t $OPTARG"; gsargs="-sPAPERSIZE=$OPTARG";;
    s) action=sweave;;
    v) action=view;;
    x) action=clean;;
  esac
done
shift $((OPTIND-1))

dviargs="$dviargs -P pdf"
gsargs="$gsargs -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress \
-dCompatibilityLevel=1.4 -dSAFER -q -o"
# Rargs="--no-init-file --slave"
tex="${1%.*}".tex
dvi="${1%.*}".dvi
ps="${1%.*}".ps
pdf="${1%.*}".pdf
Rnw=`basename "$1"`
Rnwpdf="${Rnw/%.Rnw/.pdf}"
dir=`dirname "$1"`

case $action in
  # TeX-clean-default-intermediate-suffixes from AUCTeX tex.el
  clean)
    rm -f "${1%.*}".aux "${1%.*}".bbl "${1%.*}".blg "${1%.*}".brf "${1%.*}".fot
    rm -f "${1%.*}".glo "${1%.*}".gls "${1%.*}".idx "${1%.*}".ilg "${1%.*}".ind
    rm -f "${1%.*}".lof "${1%.*}".log "${1%.*}".lot "${1%.*}".nav "${1%.*}".out
    rm -f "${1%.*}".snm "${1%.*}".toc "${1%.*}".url "${1%.*}".synctex.gz
    rm -f "${1%.*}".bcf "${1%.*}".run.xml "${1%.*}".fls "{1%.*}"-blx.bib
    rm -f "${1%.*}".fdb_latexmk;;
  compile) latex $tex; dvips $dviargs $dvi; gs $gsargs $pdf $ps;;
  help) help;;
  knit) if [[ "${1##*.}" == .tex ]]; then
          echo "Error: knitr file should not be named .tex"; exit
        fi
        cd $dir; Rscript --vanilla -e "library(knitr);knit('$Rnw')"
        latexmk -g -pdf $tex;;
  sweave) if [[ "${1##*.}" == .tex ]]; then
            echo "Error: sweave file should not be named .tex"; exit
          fi
          cd $dir
          Rscript --vanilla -e "Sweave('$Rnw',debug=TRUE,encoding='UTF-8')"
          latexmk -g -pdf $tex;;
  view) if [[ -f $pdf ]]; then ghostview $pdf; else ghostview $Rnwpdf; fi;;
esac
