#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: book [-r refpage] file"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   book [-r refpage] file                                           #
###                                                                            #
### Purpose:  Append empty page to PDF book                                    #
###                                                                            #
### Args:     refpage is the page used to set height and width of empty page   #
###           file is a PDF document                                           #
###                                                                            #
### Notes:    If -r is not supplied, page 42 is used as the reference page     #
###                                                                            #
### Warning:  Filename must not contain spaces                                 #
###                                                                            #
### Requires: pdfinfo, pdftk, pdf.blank(), sejda-console                       #
###                                                                            #
### Returns:  New file "$file_book.pdf" is created in current directory        #
###                                                                            #
################################################################################

ref=42
while getopts "r:" A; do
  case $A in
    r) ref=$OPTARG;;
  esac
done
shift $((OPTIND-1))

# 1  Full target path and short prefix
book="${1%.*}_book.pdf"
page="$TMPDIR/${1%.*}_page.pdf"
empty="$TMPDIR/${1%.*}_empty.pdf"

# 2  Set width and height
rm -f "$page"
pdftk "$1" cat "$ref" output "$page"
if [[ -f "$page" ]]; then true; else echo "Consider passing -r"; exit 1; fi
width=`pdfinfo "$page" | gawk '/Page size/ {print $3}'`
height=`pdfinfo "$page" | gawk '/Page size/ {print $5}'`

# 3  Create _empty.pdf
Rscript --slave -e \
"arni::pdf.blank('$empty', as.numeric('$width')/72, as.numeric('$height')/72)"

# 4  Merge book and empty page
sejda-console merge -f "$1" "$empty" -o "$book" --overwrite

# 5  Delete temp files
rm "$empty"
rm "$page"
