#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: cleanboot [-f]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cleanboot [-f]                                                   #
###                                                                            #
### Purpose:  Clean TAF bootstrap directory                                    #
###                                                                            #
### Args:     f removes bootstrap/library completely                           #
###                                                                            #
### Requires: R, icesTAF                                                       #
###                                                                            #
### Returns:  Removes directories                                              #
###                                                                            #
################################################################################

if [[ -z $1 ]]; then
  Rscript --vanilla -e "icesTAF::clean('bootstrap')"
else
  Rscript --vanilla -e "icesTAF::clean(c('bootstrap/data','bootstrap/library',\
                        'bootstrap/library:','bootstrap/software'))"
fi
