#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: cleanboot [-f]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cleanboot [-f]                                                   #
###                                                                            #
### Purpose:  Clean TAF bootstrap directory                                    #
###                                                                            #
### Args:     f removes bootstrap/data, bootstrap/library, and                 #
##              bootstrap/software completely                                  #
###                                                                            #
### Requires: R, TAF                                                           #
###                                                                            #
### Returns:  Removes directories                                              #
###                                                                            #
################################################################################

if [[ -z $1 ]]; then
  Rscript --vanilla -e "TAF::clean('boot')"
else
  Rscript --vanilla -e "TAF::clean('boot', force=TRUE)"
fi
