#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: clone repo"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   clone repo                                                       #
###                                                                            #
### Purpose:  Clone repository without opening a browser to copy address       #
###                                                                            #
### Args:     repo is a GitHub repository in the format owner/repository       #
###                                                                            #
### Requires: git                                                              #
###                                                                            #
### Returns:  Local working directory                                          #
###                                                                            #
################################################################################

repo=$1

# Prepend git@github.com: and append .git if needed
if [[ ! $repo =~ github.com ]]; then repo=git@github.com:$repo; fi
if [[ ${repo:(-4)} != .git ]]; then repo=$repo.git; fi

git clone $repo
