#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: "cpu [-n freq] [-r]'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cpu [-n freq] [-r]                                               #
###                                                                            #
### Purpose:  Watch CPU speed and temperature                                  #
###                                                                            #
### Args:     freq determines the update interval in seconds (default 1)       #
###           r shows range, only the lowest and highest value                 #
###                                                                            #
### Requires: cpustatus                                                        #
###                                                                            #
### Returns:  CPU speed and temperatures                                       #
###                                                                            #
################################################################################

freq=1
range=0
while getopts "n:r" A; do
  case $A in
    n) freq=$OPTARG;;
    r) range=1;;
  esac
done
shift $((OPTIND-1))

if [[ $range == 0 ]]; then
  watch -n $freq -t cpustatus
else
  watch -n $freq -t cpustatus -r
fi
