#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: "cpumonitor [-n freq] [-o file] [-t]'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cpumonitor [-n freq] [-o file] [-t]                              #
###                                                                            #
### Purpose:  Monitor CPU speed, temperature, and fan speed                    #
###                                                                            #
### Args:     freq is the update interval in seconds (default 1)               #
###           file is an output file                                           #
###           t adds a time column                                             #
###                                                                            #
### Returns:  Shows CPU status updates                                         #
###                                                                            #
################################################################################

freq=1
unset file
time=0
while getopts "n:o:t" A; do
  case $A in
    n) freq=$OPTARG;;
    o) file=$OPTARG;;
    t) time=1;;
  esac
done

header=`cpustatus -h`
if [[ $time == 1 ]]; then header=Time,$header; fi
if [[ -z $file ]]; then
  echo $header
else
  echo $header > $file
fi

while true; do
  values=`cpustatus -s`
  if [[ $time == 1 ]]; then values=`date '+%H:%M:%S'`,$values; fi
  if [[ -z $file ]]; then
    echo $values
  else
    echo $values >> $file
  fi
  sleep $freq
done
