#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: "cpumon [-d duration] [-i interval]'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cpumon [-d duration] [-i interval]                               #
###                                                                            #
### Purpose:  Monitor CPU speed, temperature, and fan speed                    #
###                                                                            #
### Args:     duration is how long to monitor in seconds (default infinity)    #
###           interval is the update interval in seconds (default 1)           #
###                                                                            #
### Returns:  Shows CPU status updates                                         #
###                                                                            #
################################################################################

duration=0
interval=1
while getopts "d:i:" A; do
  case $A in
    d) duration=$OPTARG;;
    i) interval=$OPTARG;;
  esac
done

header=Time,`cpustatus -h`
echo $header

while true; do
  values=$SECONDS,`cpustatus -s`
  echo $values
  if (( $duration != 0 )) && (( $SECONDS >= $duration )); then
    break
  fi
  sleep $interval
done
