#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: "cpumonitor [-n freq] [-o file]'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cpumonitor [-n freq] [-o file]                                   #
###                                                                            #
### Purpose:  Monitor CPU speed, temperature, and fan speed                    #
###                                                                            #
### Args:     freq is the update interval in seconds (default 1)               #
### Args:     file is an output file                                           #
###                                                                            #
### Returns:  Shows CPU status updates                                         #
###                                                                            #
################################################################################

freq=1
unset file
while getopts "n:o:" A; do
  case $A in
    n) freq=$OPTARG;;
    o) file=$OPTARG;;
  esac
done

# Header
if [[ -z $file ]]; then
  cpustatus -h
else
  cpustatus -h > $file
fi

# Values
while true; do
  if [[ -z $file ]]; then
    cpustatus -s
  else
    cpustatus -s >> $file
  fi
  sleep $freq
done
