#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: "cpuspeed [-r]'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cpuspeed  [-r]                                                   #
###                                                                            #
### Purpose:  Show current CPU speed of each core                              #
###                                                                            #
### Args:     r shows range, only the speed of slowest and fastest cores       #
###                                                                            #
### Returns:  CPU speeds                                                       #
###                                                                            #
################################################################################

range=0
watch=0
while getopts "r" A; do
  case $A in
    r) range=1;;
  esac
done
shift $((OPTIND-1))

if [[ $range == 0 ]]; then
  cat /proc/cpuinfo | grep --color=never MHz | cut -c12-15 | sort -n
else
  cat /proc/cpuinfo | grep --color=never MHz | cut -c12-15 | sort -n | \
    sed -n '1p;$p' | paste -s
fi
