#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: "cpustatus [-h] [-r] [-s]'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   cpustatus [-h] [-r] [-s]                                         #
###                                                                            #
### Purpose:  Show current CPU frequency, temperature, and fan speed           #
###                                                                            #
### Args:     h shows header that describes the single-line format             #
###           r shows output in range format, lowest and highest value         #
###           s shows output in single-line format                             #
###                                                                            #
### Requires: cpufan, cpufreq, cputemp                                         #
###                                                                            #
### Returns:  CPU frequency, temperature, and fan speed                        #
###                                                                            #
################################################################################

format=default
while getopts "hrs" A; do
  case $A in
    h) format=header;;
    r) format=range;;
    s) format=single;;
  esac
done
shift $((OPTIND-1))

sensors | grep -q RPM
rpm=$?

if [[ $format == default ]]; then
  echo "*** Freq"
  cpufreq
  echo
  echo "*** Temp"
  cputemp
  if [[ $rpm == 0 ]]; then
    echo
    echo "*** Fan"
    cpufan
  fi

elif [[ $format == range ]]; then
  echo -n "Freq    "
  cpufreq -r | sed 's/\t/  /'
  echo -n "Temp    "
  cputemp -r | sed 's/\t/  /'
  if [[ $rpm == 0 ]]; then
    echo -n "Fan   "
    cpufan -r | sed 's/\t/  /'
  fi

elif [[ $format == single ]]; then
  out=`cpufreq | paste -s -d,`
  out=$out,`cputemp | paste -s -d,`
  if [[ $rpm == 0 ]]; then
    out=$out,`cpufan | paste -s -d,`
  fi
  echo $out | tr -d " "

elif [[ $format == header ]]; then
  nfreq=`cpufreq | wc -l`
  ntemp=`cputemp | wc -l`
  out=`seq -s, "$nfreq" | sed 's/[0-9]\+/Freq&/g'`
  out=$out,`seq -s, "$ntemp" | sed 's/[0-9]\+/Temp&/g'`
  if [[ $rpm == 0 ]]; then
    nfan=`cpufan | wc -l`
    out=$out,`seq -s, "$nfan" | sed 's/[0-9]\+/Fan&/g'`
  fi
  echo $out
fi
