#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: ediff file1 file2"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   ediff [-nw] file1 file2                                          #
###                                                                            #
### Purpose:  Compare files in Emacs ediff                                     #
###                                                                            #
### Args:     file1 and file2 are files to compare                             #
###           nw opens Emacs ediff in terminal                                 #
###                                                                            #
### Requires: Emacs                                                            #
###                                                                            #
### Returns:  Opens files in Emacs ediff                                       #
###                                                                            #
################################################################################

## Support long arg
unset nw
if [[ $1 == "-nw" ]]; then
  nw="-nw"
  shift
fi

file1=$1
file2=$2
script=`mktemp`

echo "(ediff-files \"$file1\" \"$file2\")" > $script
echo "(delete-file \"$script\")" >> $script

emacs $nw -l $script
