#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: hafget file(s)"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   hafget file(s)                                                   #
###                                                                            #
### Purpose:  Fetch file from Hafurtask                                        #
###                                                                            #
### Args:     file is the file to send                                         #
###                                                                            #
###                                                                            #
### Requires: scp                                                              #
###                                                                            #
### Returns:  Copies file from Hafurtask to current directory                  #
###                                                                            #
################################################################################

scp -p "hafurtask.hafro.is:$*" .
