#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: http"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   http                                                             #
###                                                                            #
### Purpose:  Serve current directory tree at http://$HOSTNAME:8000            #
###                                                                            #
### Requires: python                                                           #
###                                                                            #
### Returns:  Initiates web service                                            #
###                                                                            #
################################################################################

echo http://$HOSTNAME:8000

python3 -m http.server

# python2 -m SimpleHTTPServer
