#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: lfh [file]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   lfh [-N] [file]                                                  #
###                                                                            #
### Purpose:  Show the most recent Git log entries, formatted to single lines  #
###                                                                            #
### Args:     N is the maximum number of entries to show (default 10)          #
###           file is a folder or file inside a Git repository                 #
###                                                                            #
### Notes:    lfh = log-full | head                                            #
###                                                                            #
### Requires: git                                                              #
###                                                                            #
### Returns:  Git log entries are shown on screen                              #
###                                                                            #
################################################################################

# Parse special arg -N
if [[ ${1:0:1} == - ]]; then
  n=${1:1}; shift
else
  n=5
fi

# Parse file arg
if [[ -z $1 ]]; then file=; else file=$1; fi

# Show log
if git log HEAD~$n..HEAD --format="$GIT_FORMAT" $file &> /dev/null; then
  git log HEAD~$n..HEAD --format="$GIT_FORMAT" $file
else
  git log --format="$GIT_FORMAT" $file
fi
