#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: lfh [file]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   lfh [-N] [file]                                                  #
###                                                                            #
### Purpose:  Show the most recent Git log entries, formatted to single lines  #
###                                                                            #
### Args:     N is the maximum number of entries to show (default 10)          #
###           file is a folder or file inside a Git repository                 #
###                                                                            #
### Notes:    lfh = log-full | head                                            #
###                                                                            #
### Requires: git                                                              #
###                                                                            #
### Returns:  Git log entries are shown on screen                              #
###                                                                            #
################################################################################

# Compared to a previous implementation using HEAD~N..HEAD to select the number
# of lines, this version shows the right number of lines, both for a repo and
# for a specific file. The HEAD~N..HEAD version had nicer color output but in
# many cases showed the wrong number of lines, even with the git log options
# --no-merges or --first-parent.

# Parse special arg -N
if [[ ${1:0:1} == - ]]; then
  N=${1:1}; shift
else
  N=10
fi

# Parse file arg
if [[ -z $1 ]]; then file=; else file=$1; fi

# Show log
git log --format="$GIT_FORMAT" $file | head -$N
