#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: lorem [n]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   lorem [n]                                                        #
###                                                                            #
### Purpose:  Show dummy paragraphs "Lorem ipsum ..."                          #
###                                                                            #
### Args:     n is the number of paragraphs (default 1)                        #
###                                                                            #
### Returns:  Shows text on screen                                             #
###                                                                            #
################################################################################

if [[ -z $1 ]]; then
  n=1
else
  n="${1//-/}"
fi

txt="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod \
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, \
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo \
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse \
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non \
proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

for i in `seq $((n-1))`; do echo $txt; echo; done
echo $txt
