#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: lR [dir]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   lR [dir]                                                         #
###                                                                            #
### Purpose:  List filenames recursively                                       #
###                                                                            #
### Args:     dir is the directory or file to show (default is current dir)    #
###                                                                            #
### Notes:    Similar to ls -AR, but more compact                              #
###                                                                            #
### Requires: find                                                             #
###                                                                            #
### Returns:  Filenames are shown, one line per file                           #
###                                                                            #
################################################################################

find $1 -type f | sed 's/^\.\///'
