#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: o repo"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   o repo                                                           #
###                                                                            #
### Purpose:  Clone OFP-SAM repository by typing 'o repo' instead of           #
###             'clone PacificCommunity/ofp-sam-repo' and then rename to repo  #
###                                                                            #
### Requires: git                                                              #
###                                                                            #
### Returns:  Clones GitHub repository to local folder and renames it          #
###                                                                            #
################################################################################

git clone git@github.com:PacificCommunity/ofp-sam-$1
mv -v ofp-sam-$1 $1
