#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: ofp-sam repo"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   ofp-sam repo                                                     #
###                                                                            #
### Purpose:  Clone OFP-SAM repository by typing 'ofp-sam repo' instead of     #
###             'clone PacificCommunity/ofp-sam-repo' and then rename to repo  #
###                                                                            #
### Requires: clone                                                            #
###                                                                            #
### Returns:  Clones GitHub repository to local folder and renames it          #
###                                                                            #
################################################################################

clone PacificCommunity/ofp-sam-$1
mv -v ofp-sam-$1 $1
