#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: pdfclean [-n] file"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   pdfclean [-n] file                                               #
###                                                                            #
### Purpose:  Replace PDF stamp like '(Downloaded by ...)' with spaces         #
###                                                                            #
### Args:     n does not backup in $TMPDIR                                     #
###           file is a PDF document                                           #
###                                                                            #
### Notes:    The default is to write copy a backup of the file in $TMPDIR.    #
###           The -n option is useful if the user has limited write access.    #
###                                                                            #
### Requires: pdftk, Emacs with Lisp function `pdf-clean' in .emacs            #
###                                                                            #
### Returns:  Overwrites original PDF file, after removing stamps              #
###                                                                            #
################################################################################

backup=0
while getopts "n" A; do
  case $A in
    n) backup=1;;
  esac
done
shift $((OPTIND-1))

backupfile=$TMPDIR/clean.pdf
clean="${1%.*}"_clean.pdf

if [[ backup == 1 ]]; then
  cp "$1" $backupfile
fi

pdftk "$1" output "$clean" uncompress
# qpdf --stream-data=uncompress "$1" "$clean" 2> /dev/null
emacs "$clean" -nw --eval "(pdf-clean)" --eval "(save-buffers-kill-terminal t)"
pdftk "$clean" output "$1" compress
# qpdf "$clean" "$1"
rm "$clean"
