#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: Rall [-f] [-i] [-n] [-r] PKG"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   Rall [-f] [-i] [-n] [-r] PKG                                     #
###                                                                            #
### Purpose:  Roxygenize, build, check, and optionally install R package       #
###                                                                            #
### Args:     f skips the check (fast build)                                   #
###           i installs the package in the default library                    #
###           n builds without vignettes                                       #
###           r connects to remote CRAN server for a full --as-cran check      #
###           PKG is an R package directory                                    #
###                                                                            #
### Requires: R                                                                #
###                                                                            #
### Returns:  Checks package and creates PKG.Rcheck directory                  #
###                                                                            #
################################################################################

args=
check=1
install=0
vignettes=
while getopts "finr" A; do
  case $A in
    f) check=0;;
    i) install=1;;
    n) vignettes=-n;;
    r) args=-r;;
  esac
done
shift $((OPTIND-1))

Roxy $1
Rbuild $vignettes $1
if [[ $check == 1 ]]; then Rcheck $args $1; fi
if [[ $install == 1 ]]; then Rinstall $1; fi
