#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: Rall [-d] [-f] [-i] [-n] [-r] [-s] PKG";
            echo "  -d  disable resave";
            echo "  -f  fast build";
            echo "  -i  install";
            echo "  -n  no vignette";
            echo "  -r  remote check";
            echo "  -s  skip roxygenize"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   Rall [-d] [-f] [-i] [-n] [-r] [-s] PKG                           #
###                                                                            #
### Purpose:  Roxygenize, build, check, and optionally install R package       #
###                                                                            #
### Args:     d disables data resave                                           #
###           f skips the check (fast build)                                   #
###           i installs the package in the default library                    #
###           n builds without vignettes                                       #
###           r connects to remote CRAN server for a full --as-cran check      #
###           s skip the roxygenize step to build and check an old package     #
###           PKG is an R package directory                                    #
###                                                                            #
### Requires: R                                                                #
###                                                                            #
### Returns:  Checks package and creates PKG.Rcheck directory                  #
###                                                                            #
################################################################################

ascran=
check=1
install=0
resave=
roxygenize=1
vignettes=
while getopts "dfinrs" A; do
  case $A in
    d) resave=-d;;
    f) check=0;;
    i) install=1;;
    n) vignettes=-n;;
    r) ascran=-r;;
    s) roxygenize=0;;
  esac
done
shift $((OPTIND-1))

if [[ $roxygenize == 1 ]]; then roxy $1; fi
Rbuild $resave $vignettes $1
if [[ $check == 1 ]]; then Rcheck $ascran $1; fi
if [[ $install == 1 ]]; then Rinstall $1; fi
