#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: Rbuild [-c] [-d] [-i] [-n] PKG";
            echo "  -c  compact twice";
            echo "  -d  disable resave";
            echo "  -i  install";
            echo "  -n  no vignette"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   Rbuild [-c] [-d] [-i] [-n] PKG                                   #
###                                                                            #
### Purpose:  Build R package without typing                                   #
###             R --vanilla CMD build --compact-vignettes --resave-data PKG    #
###                                                                            #
### Args:     c compacts vignettes with gs+qpdf (default is only qpdf)         #
###           d disables data resave                                           #
###           i installs the package in the default library                    #
###           n builds without vignettes                                       #
###           PKG is an R package directory                                    #
###                                                                            #
### Requires: R                                                                #
###                                                                            #
### Returns:  Builds package and creates PKG_x.y-z.tar.gz in current directory #
###                                                                            #
################################################################################

compact=--compact-vignettes
install=0
resave=--resave-data
vignettes=
while getopts "cdin" A; do
  case $A in
    c) compact=--compact-vignettes=both;;
    d) resave=;;
    i) install=1;;
    n) vignettes=--no-build-vignettes;;
  esac
done
shift $((OPTIND-1))

R --vanilla CMD build $compact $vignettes $resave $1
if [[ $install == 1 ]]; then Rinstall $1; fi
