#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: Rbuild PKG"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   Rbuild PKG                                                       #
###                                                                            #
### Purpose:  Build R package without typing                                   #
###             R --vanilla CMD build --compact-vignettes --resave-data PKG    #
###                                                                            #
### Args:     PKG is an R package directory                                    #
###                                                                            #
### Requires: R                                                                #
###                                                                            #
### Returns:  Checks package and creates PKG.Rcheck directory                  #
###                                                                            #
################################################################################

R --vanilla CMD build --compact-vignettes --resave-data $1
