#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: Rcheck [-f] [-r] PKG"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   Rcheck [-f] [-r] PKG                                             #
###                                                                            #
### Purpose:  Check R package without typing                                   #
###             env _R_CHECK_CRAN_INCOMING_REMOTE_=FALSE R --vanilla CMD check #
###             --as-cran PKG_x.y-z.tar.gz                                     #
###                                                                            #
### Args:     f runs a plain R CMD check                                       #
###           r connects to remote CRAN server for a full --as-cran check      #
###           PKG is an R package directory                                    #
###                                                                            #
### Requires: R                                                                #
###                                                                            #
### Returns:  Checks package and creates PKG.Rcheck directory                  #
###                                                                            #
################################################################################

ascran=--as-cran
remote=FALSE
while getopts "fr" A; do
  case $A in
    f) unset ascran;;
    r) remote=TRUE;;
  esac
done
shift $((OPTIND-1))

# Look for PKG_x.y-z.tar.gz (highest version if many are found)
targz=`ls -mr $1_*`
targz=`echo $targz | sed 's/,.*//'`

env _R_CHECK_CRAN_INCOMING_REMOTE_=$remote ~/bin/R --vanilla CMD check $ascran \
$targz
