#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: Rcheck [-a] [-r] PKG";
            echo "  -a runs --as-cran";
            echo "  -r runs --as-cran and checks remotes"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   Rcheck [-a] [-r] PKG                                             #
###                                                                            #
### Purpose:  Check R package with the default basic 'R CMD check' but with    #
###           flags to run things like                                         #
###             env _R_CHECK_CRAN_INCOMING_REMOTE_=FALSE R --vanilla CMD check #
###             --as-cran PKG_x.y-z.tar.gz                                     #
###                                                                            #
### Args:     a runs R CMD check --as-cran without checking remotes            #
###           r runs R CMD check --as-cran with --vanilla and checks remotes   #
###           PKG is an R package directory                                    #
###                                                                            #
### Notes:    Setting the environment variable _R_CHECK_CRAN_INCOMING_REMOTE_  #
###           to FALSE speeds up the --as-cran check, so we use that if user   #
###           passes -a but go with a full CRAN check if user passes -r.       #
###                                                                            #
###           Using --vanilla slows down the check as it doesn't take          #
###           advantage of CRAN mirror settings in .Rprofile, so we don't use  #
###           --vanilla if user passes no flags or -a but we use it if user    #
###           passes -r.                                                       #
###                                                                            #
###           The three cases are:                                             #
###           1) Rcheck => R CMD check                                         #
###           2) Rcheck -a =>                                                  #
###              env R_CHECK_CRAN_INCOMING_REMOTE_=FALSE R CMD check --as-cran #
###           3) Rcheck -r => R --vanilla CMD check --as-cran                  #
###                                                                            #
### Requires: R                                                                #
###                                                                            #
### Returns:  Checks package and creates PKG.Rcheck directory                  #
###                                                                            #
################################################################################

unset ascran
unset env
unset vanilla
while getopts "ar" A; do
  case $A in
    a) ascran=--as-cran; env="env R_CHECK_CRAN_INCOMING_REMOTE_=FALSE";;
    r) ascran=--as-cran; vanilla=--vanilla;;
  esac
done
shift $((OPTIND-1))

folder=${1%/}  # shave off trailing /

# Look for PKG_x.y-z.tar.gz (highest version if many are found)
targz=`ls -mr ${folder}_*`
targz=`echo $targz | sed 's/,.*//'`

$env R $vanilla CMD check $ascran $targz
