#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: rmlarge [-k 1024] directory"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:  rmlarge [-k 1024] directory                                       #
###                                                                            #
### Purpose: Remove large files from a directory                               #
###                                                                            #
### Args:    k is the threshold file size in KB                                #
###                                                                            #
### Notes:   Implemented for Emacs backup system, subdirs are left intact      #
###                                                                            #
### Returns: Removes files exceeding threshold from directory                  #
###                                                                            #
################################################################################

max=1024
while getopts "k:" A; do
  case $A in
    k) max=$OPTARG;;
  esac
done
shift $((OPTIND-1))

findargs="-maxdepth 1 -size +${max}k -type f -exec rm {} ;"
find $1 $findargs
