#!/bin/bash
shopt -s expand_aliases
################################################################################
###                                                                            #
### Script:   Rscript [options]                                                #
###                                                                            #
### Purpose:  Run newest Rscript                                               #
###                                                                            #
### Args:     See Rscript documentation                                        #
###                                                                            #
### Requires: Rscript                                                          #
###                                                                            #
### Returns:  Runs Rscript                                                     #
###                                                                            #
################################################################################

# 1  Look for newest Rscript executable
if [[ -f /opt/bin/Rscript ]]; then     # Linux, newest R in /opt
  Rscript=/opt/bin/Rscript
elif [[ -f ~/opt/bin/Rscript ]]; then  # Linux, newest R in ~/opt
  Rscript=~/opt/bin/Rscript
elif [[ -d /c/gnu/r/bin ]]; then       # Windows Git Bash, R in c:/gnu/r
  Rscript=/c/gnu/r/bin/Rscript.exe
else
  Rscript=/usr/bin/Rscript             # Linux, system R
fi

# 2  Run
# Quote because args can have spaces
$Rscript "$@"
