#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: taf [-q] script"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   taf -q [script]                                                  #
###                                                                            #
### Purpose:  Run all TAF scripts, or a specific script                        #
###                                                                            #
### Args:     q means quiet, suppress messages                                 #
###           script is R script to run                                        #
###                                                                            #
### Requires: R, icesTAF                                                       #
###                                                                            #
### Returns:  Runs script                                                      #
###                                                                            #
################################################################################

quiet=FALSE
while getopts "q" A; do
  case $A in
    q) quiet=TRUE;;
  esac
done
shift $((OPTIND-1))

if [[ -z $1 ]]; then
  Rscript --vanilla -e "icesTAF::sourceAll(quiet=$quiet)"
else
  Rscript --vanilla -e "icesTAF::sourceTAF(\"$1\", quiet=$quiet)"
fi
