#!/bin/bash
shopt -s expand_aliases
alias help='echo "Usage: taf [script]"'
if [[ "$1" == "--help" ]]; then help; exit; fi
################################################################################
###                                                                            #
### Script:   taf [script]                                                     #
###                                                                            #
### Purpose:  Run all TAF scripts, or a specific script                        #
###                                                                            #
### Args:     script is R script to run                                        #
###                                                                            #
### Requires: R, icesTAF                                                       #
###                                                                            #
### Returns:  Runs script(s)                                                   #
###                                                                            #
################################################################################

## Add .R if user omitted file extension
script=${1%.*}.R

if [[ -z $1 ]]; then
  Rscript --vanilla -e "icesTAF::sourceAll()"
else
  Rscript --vanilla -e "icesTAF::sourceTAF(\"$script\")"
fi
